---
- name: Configure homelab.
  hosts: all
  become: true
  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update package cache.
      ansible.builtin.package:
        update_cache: yes

  roles:
    - role: geerlingguy.docker

  tasks:
    - import_tasks: tasks/main.yml
    - import_tasks: tasks/dotfiles.yml
      become: false
    - import_tasks: tasks/virtualization.yml
