---
- name: Configure homelab.
  hosts: all
  become: true
  vars_files:
    - vars.yml

  roles:
    - role: geerlingguy.docker

  tasks:
    - import_tasks: tasks/main.yml
    - import_tasks: tasks/dotfiles.yml
      become: false
