---
- name: Configure homelab.
  hosts: all
  become: true
  vars_files:
    - vars.yml

  pre_tasks:
    - name: Update package cache.
      ansible.builtin.package:
        update_cache: yes
      tags: ['always']

  roles:
    - role: geerlingguy.docker
      tags: ['docker']

  tasks:
    - import_tasks: tasks/main.yml
      tags: ['main']
    - import_tasks: tasks/storage.yml
      tags: ['storage']
    - import_tasks: tasks/dotfiles.yml
      become: false
      tags: ['dotfiles']
    - import_tasks: tasks/virtualization.yml
      tags: ['virt']
